### ISSUE TITLE
Claude V2

### ISSUE THREAD

**Issue by aaweb** [themaximal1st/ai.js#1]
Dear Maximal1st team,

Awesome repo! Been using the component for a few weeks and its amazing. I wonder why this repo is not much much more popular?

I was wondering if there are plans to add Claude V2. I tried using it by just adjusting the model string but always receive an error. Thanks for the update. If this is not actively developed, it's OK as well, but please let me know as I'd have to look for another solution (even though I love the elegance of this one)

Andy

**Comment by themaximalist** [comment]
Hey Andy, thanks for letting me know. AI.js is still in active development and I'll look into getting Claude v2 working.

 I haven't promoted AI.js much, but I should, I find it very helpful for my projects as well.

If you're able to produce an error, please let me know what you're seeing, otherwise I will aim to get an update out for Claude2 soon!

**Comment by aaweb** [comment]
Thanks for the awesome work!

It does work in CLI:
```
> ai the color of the sky is --service anthropic --model claude-2 
```

I think the problem might be streaming though. Here the error I get when I change the model from GPT to claude (1 or 2).

![image](https://github.com/themaximal1st/ai.js/assets/121862/5ff8f3a6-9b38-4c0c-a9a0-1f260e295909)

I do get the same BTW when using it with `claude-1`, so it probably is more of a streaming issue than a `claude-2` one. Is that something that is supposed to work already in the library?

**Comment by aaweb** [comment]
@themaximal1st Hey there. Just wanted to check if you had a quick feedback on whether streaming is supposed to work for Claude (also v1) or if I should keep debugging on my end.

Thanks a lot! Have a wonderful day.

**Comment by themaximalist** [comment]
Yes streaming works with Claude (v1), the examples/tests should show how
to do this. Let me know if it doesn’t work.

**Comment by aaweb** [comment]
Thanks, I narrowed it down. Claude has no notion of a system message, which is why this did not work and cause the error mentioned above (which is not very descriptive unfortunately):
```
      const messages = [
        { role: "system", content: "Give all answers in uppercase." },
        { role: "user", content: "Tell a one liner joke." },
      ];
      const ai = new AI(messages, options);
      const stream = await ai.send();

```

To make it work for both openai and anthropic, I just iterate the messages and change system roles to user. Like this is also works with `claude-2`.

Thanks a lot for the help!

Maybe worth a note in the README or even better a test/check that informs the API user similar to when trying to use other unsupported features (like functions).
